#!/usr/bin/env bash

function main {
  source shflags
  DEFINE_boolean oneline "$FLAGS_FALSE" \
                         "Output on one line" o
  DEFINE_string limit    "nothing-$RANDOM" \
                         "limit to a subset of hosts" l
  DEFINE_string mod      "" \
                         "Ansible module" m
  DEFINE_string margs    "" \
                         "Ansible module arguments" a
  FLAGS "$@" || exit $?
  set -- ${FLAGS_ARGV:+"${FLAGS_ARGV[@]}"}

  exec ansible ${opt_ansible:+"${opt_ansible[@]}"} \
    ${FLAGS_oneline:+-o } \
    ${FLAGS_limit:+-l "$FLAGS_limit" } \
    ${FLAGS_mod:+-m "$FLAGS_mod" } \
    ${FLAGS_margs:+-a "$FLAGS_margs" } \
    "$@" \
    all
}

source sub "$0" "$@"
